language: node_js
node_js:
  - node

dist: bionic
sudo: required
before_script:
  - npm install -g @angular/cli
  - npm install -g now
script:
  - ng build --prod
deploy:
  provider: s3
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: "$AWS_SECRET_KEY"
  bucket: "foodsaver"
  skip_cleanup: true
  local_dir: dist/FoodSaver
  on:
    all_branches: true
    condition: $TRAVIS_BRANCH =~ ^release\/.*$
  acl: public_read
